version: 2

general:
    branches:
        only:
        - master
        - dev

jobs:
    build:
        machine:
            java:
                version: oraclejdk8
        steps:
            - ant deployCodeCheckOnly