version: 2.0

general:
    branches:
        only:
        - master
        - dev

machine:
    java:
        version: oraclejdk8

build:
    - ant deployCodeCheckOnly
# test:
#     override:
#         - ant deployCodeCheckOnly
#             timeout: 600
# machine:
#   java:
#     version: oraclejdk8
# test:
#   override:
#     - ant -lib lib/ Build:
#         timeout: 600